### PR TITLE
Fix plugin

### PR DESCRIPTION
**Pull request by Maxopoly**
I started out with fixing duels and ended up rewriting this entire mess of a plugin. Highlights include:

- Proper maven folder structure
- Listener are in a single class instead of being spread out all over the place
- All database stuff is in one class instead of being spread out all over the place
- Database now uses CivModCores handling instead of reinventing the wheel the 50th time
- Commands use CivModCores handling, each command has it's own class instead of a single giant switch case monster
- Main plugin class is no longer what should be three classes, similar applies to some other classes as well
- Classes are properly subdivided into packages
- Reformatted entire project according to style guide

- Duels work, including an elo system
- You can set warps, which will be randomly picked for duels. The previous system of dynamically creating maps was an awful idea.
- You can go into spectator mode via command, which gives you a set of config defined permissions temporarily

---

I'm still testing this and messing around a bit with it, but already wanted to make this PR now in case someone actually wants to take a look over it.

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Haven't looked at it yet but I already love it

**Comment by TealNerd** [comment]
👏

**Comment by ProgrammerDan** [comment]
Any upstream changes from getting CivClassicsPvP running? @Maxopoly

**Comment by ProgrammerDan** [comment]
FWIW looks mostly good, only thing that gave me pause was the missing inv cleansing on gamemode change and login, which in 1.12 are quite important, due to "toolbars" feature allowing basically _any_ item, including NBT, to be generated by players; so a pvp "gm1" mode zone exposes significant abuse without it.

Might have just missed 'em, not a big deal. Everything else looks good, so I'll just wait on word of other upstream fixes before merging.

**Comment by ProgrammerDan** [comment]
@Maxopoly Last call for upstream fixes from your launch?

**Pull request merged**
